apiVersion: v1
kind: Pod
metadata: 
  name: website-deployment
metadata: 
  name: website
  labels: 
    app: website
    rel: dev
spec: 
  containers:
  - name: website-build
    image: burakkiymaz/website-build
    volumeMounts:
    - mountPath: /var/www/burakkiymaz/_site
      name: website-volume

  - name: website-publish
    image: burakkiymaz/website-publish
    volumeMounts:
    - mountPath: /var/www/burakkiymaz/_site
      name: website-volume
    ports:
    - name: website-port
      containerPort: 80
      protocol: TCP

  volumes:
  - name: website-volume    

