apiVersion: v1
kind: Service
metadata:
  name: website-service
spec: 
  ports: 
  - port: 80
    nodePort: 30080
    targetPort: website-port
    protocol: TCP
  selector:
    app: website
  type: NodePort

