apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
        name: website-argo-application
        namespace: argocd
spec:
        project: default

        source:
                repoURL: https://github.com/burakkiymaz/kubernetesTest.git
                targetRevision: HEAD
                path: website/kubernetes

        destination:
                server: https://kubernetes.default.svc
                namespace: website
        syncPolicy: 
                syncOptions:
                - CreateNamespace=true

                automated: 
                        selfHeal: true
                        prune: true
